version: "3"

env:
  tag_version: v0.21
  repo: avorioner
  # DOCKER_HOST: ssh://root@darklab:22

tasks:
  docker:ps:
    cmds:
      - docker ps

  docker:build:
    cmds:
      - docker build --tag darkwind8/${repo}:${tag_version} --target ${repo}-runner .

  docker:push:
    cmds:
      - docker push darkwind8/${repo}:${tag_version}

  docker:run:
    cmds:
      - docker run -it darkwind8/${repo}:${tag_version}

  docker:buildpush:
    cmds:
      - task: docker:build
      - task: docker:push

  shell:production:
    cmds:
      - ssh -i ~/.ssh/id_rsa.darklab root@production.minecraft.dd84ai.com
