version: "3"

env:
  tag_version: v0.22
  bot_repo: minecrafter
  DOCKER_HOST: ssh://root@darklab:22
  MINECRAFT_TAG: modded-1.7.10-v0.5.4
  MINECRAFT_LATEST: modded-1.7.10-latest
  CRONTAB_TAG: modded-1.7.10-crontab-v0.2.1

tasks:
  ps:
    cmds:
      - docker ps

  bot:build:
    cmds:
      - docker build --tag darkwind8/${bot_repo}:${tag_version} --target ${bot_repo}-runner .
  bot:push:
    cmds:
      - docker push darkwind8/${bot_repo}:${tag_version}
  bot:run:
    cmds:
      - docker run -it darkwind8/${bot_repo}:${tag_version}

  minecraft:build:
    cmds:
      - docker build --tag darkwind8/minecraft:${MINECRAFT_TAG} ./server_modded_1710
  minecraft:push:
    cmds:
      - docker push darkwind8/minecraft:${MINECRAFT_TAG}
      - docker tag darkwind8/minecraft:${MINECRAFT_TAG} darkwind8/minecraft:${MINECRAFT_LATEST}
      - docker push darkwind8/minecraft:${MINECRAFT_LATEST}

  minecraft:buildpush:
    cmds:
      - task: minecraft:build
      - task: minecraft:push

  minecraft:run:
    cmds:
      - docker run -it darkwind8/minecraft:${MINECRAFT_TAG}

  bot:buildpush:
    cmds:
      - task: docker:build
      - task: docker:push

  crontab:buildpush:
    cmds:
      - docker build --tag darkwind8/minecraft:${CRONTAB_TAG} ./server_modded_1710/crontab
      - docker push darkwind8/minecraft:${CRONTAB_TAG}

  shell:production:
    cmds:
      - ssh -i ~/.ssh/id_rsa.darklab root@production.minecraft.dd84ai.com
