version: "3.8"
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      # configs
      - type: bind
        source: ./configs/server.properties
        target: /code/server.properties
      - type: bind
        source: ./configs/whitelist.json
        target: /code/whitelist.json
      - type: bind
        source: ./configs/banned-ips.json
        target: /code/banned-ips.json
      - type: bind
        source: ./configs/banned-players.json
        target: /code/banned-players.json
      - type: bind
        source: ./configs/ops.json
        target: /code/ops.json

      # data
      - ./data/logs:/code/logs
      - ./data/world:/code/world
      - ./data/libraries:/code/libraries
      
      # for custom stuff u wish to copy out of running server
      - ./data/output:/code/output

      - type: bind
        source: ./data/usercache.json
        target: /code/usercache.json
    ports:
      - 25565:25565