version: "3.8"
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      # configs
      - type: bind
        source: ./configs/whitelist.json
        target: /code/whitelist.json
      - type: bind
        source: ./configs/banned-ips.json
        target: /code/banned-ips.json
      - type: bind
        source: ./configs/banned-players.json
        target: /code/banned-players.json
      - type: bind
        source: ./configs/ops.json
        target: /code/ops.json

      # data
      - ./data/logs:/code/logs
      - ./data/world:/code/world
      - ./data/AuthMe:/code/plugins/AuthMe # remembering auth of players
      - ./data/WorldGuard:/code/plugins/WorldGuard
      - ./data/WorldEdit:/code/plugins/WorldEdit
      - type: bind
        source: ./data/usercache.json
        target: /code/usercache.json
      - type: bind
        source: ./data/server.properties
        target: /code/server.properties
    ports:
      - 25565:25565
      - 4567:4567
