version: "3"
tasks:
  docker:build:
    cmds:
      - docker build --tag darkwind8/minecraft:modded-12.2-v0.1.0 .

  docker:push:
    cmds:
      - docker push darkwind8/minecraft:modded-12.2-v0.1.0

  docker:buildpush:
    cmds:
      - task: docker:build
      - task: docker:push

  clean:
    cmds:
      - sudo rm -R data/*
      - cp -R data_examples/* data/
