apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft-app
        triggerRedeploy: "1"
    spec:
      volumes:
        - name: volume-logs
          hostPath:
            path: /var/lib/darklab/minecraft/logs
            type: DirectoryOrCreate
        - name: volume-world
          hostPath:
            path: /var/lib/darklab/minecraft/world
            type: DirectoryOrCreate
        - name: volume-auth-me
          hostPath:
            path: /var/lib/darklab/minecraft/AuthMe
            type: DirectoryOrCreate
        - name: volume-world-guard
          hostPath:
            path: /var/lib/darklab/minecraft/WorldGuard
            type: DirectoryOrCreate
        - name: volume-world-edit
          hostPath:
            path: /var/lib/darklab/minecraft/WorldEdit
            type: DirectoryOrCreate
        - name: volume-usercache
          hostPath:
            path: /var/lib/darklab/minecraft/usercache.json
            type: File
        - name: volume-properties
          hostPath:
            path: /var/lib/darklab/minecraft/server.properties
            type: File
        - name: volume-configs
          configMap:
            name: game-configs
      containers:
        - name: minecraft-ctr
          image: darkwind8/minecraft:{{ .Values.image_version }}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /code/logs
              name: volume-logs
            - mountPath: /code/world
              name: volume-world
            - mountPath: /code/plugins/AuthMe
              name: volume-auth-me
            - mountPath: /code/plugins/WorldGuard
              name: volume-world-guard
            - mountPath: /code/plugins/WorldEdit
              name: volume-world-edit
            - mountPath: /code/usercache.json
              name: volume-usercache
            - mountPath: /code/server.properties
              name: volume-properties
            - name: volume-configs
              mountPath: /code/whitelist.json
              subPath: whitelist.json
            - name: volume-configs
              mountPath: /code/banned-ips.json
              subPath: banned-ips.json
            - name: volume-configs
              mountPath: /code/ops.json
              subPath: ops.json
            - name: volume-configs
              mountPath: /code/banned-players.json
              subPath: banned-players.json
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "{{.Values.hard_memory_limit}}Mi"
              cpu: "{{.Values.hard_cpu_limit}}m"
