---
- hosts: cluster
  become: yes
  gather_facts: true

  tasks:

    - name: Unarchive a file
      ansible.builtin.unarchive:
        src: backups/darkbot-{{hostvars[inventory_hostname]['varenv']}}/darklab.tgz
        dest: /var/lib/
