version: "3"

tasks:
  prod:deploy:
    cmds:
      - ansible-playbook -i hosts.prod.yml deploy.yml

  prod:download:
    cmds:
      - ansible-playbook -i hosts.prod.yml download.yml

  staging:deploy:
    cmds:
      - ansible-playbook -i hosts.staging.yml deploy.yml

  staging:download:
    cmds:
      - ansible-playbook -i hosts.staging.yml download.yml

  install:
    cmds:
      - ansible-galaxy collection install community.general

  staging:backup:
    cmds:
      - ansible-playbook -i hosts.staging.yml backup.yml

  staging:restore:
    cmds:
      - ansible-playbook -i hosts.staging.yml restore.yml

  prod:backup:
    cmds:
      - ansible-playbook -i hosts.prod.yml backup.yml

  prod:restore:
    cmds:
      - ansible-playbook -i hosts.prod.yml restore.yml
